name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v4
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    - name: Install dependencies
      run: sudo apt-get install nettle-dev libssl-dev capnproto make clang pkg-config libsqlite3-dev llvm libclang-dev
    - run: cargo build --all-features --release --verbose
    - uses: actions/upload-artifact@v4
      with:
        name: vanity_gpg
        path: ./target/release
        retention-days: 10
